# src/workflow.py
from typing import TypedDict, List, Dict, Any
from langgraph.graph import StateGraph, END
import yaml # For loading/dumping OpenAPI files
import swagger_to_openapi # For converting Swagger 2.0 to OpenAPI 3.1
import subprocess
import tempfile
# import os # Already imported below or globally
# import json # Already imported below or globally
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Define the state for the graph
class AppState(TypedDict):
    original_swagger_file_path: str # Path to the input Swagger 2.0 file
    swagger_content: Dict[str, Any] # Parsed Swagger 2.0 content
    openapi_content: Dict[str, Any] # Parsed OpenAPI 3.1 content (after conversion, before iteration)
    current_openapi_spec: Dict[str, Any] # OpenAPI spec being worked on by linter & corrector
    linter_issues: List[Dict[str, Any]] # List of issues from the linter
    # impact_log will be generated by the ImpactAnalysisAgent
    impact_log: List[Dict[str, Any]] # Log of breaking changes
    # final_openapi_spec will be the output of BestPracticesAgent
    final_openapi_spec: Dict[str, Any] # Final OpenAPI spec after all processing
    current_iteration: int # Counter for correction iterations
    max_iterations: int # Maximum number of correction iterations
    error_message: str # To store any error messages during the process
    verbose: bool # Flag for verbose logging

# --- Agent Node Placeholders ---
# These will be replaced by actual agent calls later.

import json # Explicitly import json for clarity, though yaml can handle json too.
import os

def reader_validator_node(state: AppState) -> AppState:
    print("--- Reader & Validator Node ---")
    file_path = state.get('original_swagger_file_path')

    # Initialize iteration counts and verbose flag if not already present
    state['current_iteration'] = state.get('current_iteration', 0)
    state['max_iterations'] = state.get('max_iterations', 5) # Default max iterations
    state['verbose'] = state.get('verbose', True) # Default to verbose

    if not file_path:
        state['error_message'] = "Input file path is missing."
        if state['verbose']: print(f"Error: {state['error_message']}")
        return state

    if not os.path.exists(file_path):
        state['error_message'] = f"Input file not found: {file_path}"
        if state['verbose']: print(f"Error: {state['error_message']}")
        return state

    content = None
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            file_content_str = f.read()

        try:
            # Try parsing as YAML first
            content = yaml.safe_load(file_content_str)
            if state['verbose']: print(f"Successfully parsed {file_path} as YAML.")
        except yaml.YAMLError as e_yaml:
            if state['verbose']: print(f"Failed to parse as YAML: {e_yaml}. Trying JSON...")
            try:
                # Try parsing as JSON if YAML fails
                content = json.loads(file_content_str)
                if state['verbose']: print(f"Successfully parsed {file_path} as JSON.")
            except json.JSONDecodeError as e_json:
                state['error_message'] = f"Failed to parse file as YAML or JSON: YAML error: {e_yaml}, JSON error: {e_json}"
                if state['verbose']: print(f"Error: {state['error_message']}")
                return state
    except Exception as e:
        state['error_message'] = f"Failed to read input file {file_path}: {str(e)}"
        if state['verbose']: print(f"Error: {state['error_message']}")
        return state

    if not isinstance(content, dict):
        state['error_message'] = "Parsed content is not a valid dictionary (JSON object)."
        if state['verbose']: print(f"Error: {state['error_message']}")
        return state

    state['swagger_content'] = content

    # Basic Swagger 2.0 validation
    if not content.get("swagger") == "2.0":
        state['error_message'] = "Invalid Swagger: 'swagger' field must be '2.0'."
        # Allow processing to continue to see if converter can handle it, but log error
        if state['verbose']: print(f"Validation Warning/Error: {state['error_message']}")
        # Not returning state here, as some tools might attempt conversion of slightly off versions.
        # The converter or linter will ultimately decide.
        # If strictness is required, this should return state.

    if not isinstance(content.get("info"), dict):
        state['error_message'] = (state.get('error_message') or "") + " Invalid Swagger: 'info' field must be an object. "
        if state['verbose']: print(f"Validation Warning/Error: 'info' field missing or not an object.")
        # Not returning, let converter try.

    if not isinstance(content.get("paths"), dict):
        state['error_message'] = (state.get('error_message') or "") + " Invalid Swagger: 'paths' field must be an object. "
        if state['verbose']: print(f"Validation Warning/Error: 'paths' field missing or not an object.")
        # Not returning, let converter try.

    if state.get('error_message'):
         print(f"Reader/Validator found issues: {state['error_message']}")
    elif state['verbose']:
        print("Swagger 2.0 file loaded and basic validation passed.")
        title = content.get("info", {}).get("title", "N/A")
        version = content.get("info", {}).get("version", "N/A")
        print(f"Title: {title}, Version: {version}")

    return state

def conversion_node(state: AppState) -> AppState:
    if state.get('verbose', True): print("--- Conversion Node ---")

    if state.get('error_message'): # If an error already exists from previous nodes
        if state.get('verbose', True): print("Skipping conversion due to existing error.")
        return state

    swagger_content = state.get('swagger_content')
    if not swagger_content or not isinstance(swagger_content, dict):
        state['error_message'] = "Swagger content is missing or invalid for conversion."
        if state.get('verbose', True): print(f"Error: {state['error_message']}")
        return state

    if state.get('verbose', True):
        print(f"Attempting conversion of Swagger 2.0 spec: {swagger_content.get('info', {}).get('title', 'Untitled')}")

    try:
        # The swagger-to-openapi library (by YAmfAR/Roman Hlevnoy) provides convert_from_dict
        # This was chosen based on the discussion in the prompt.
        converted_openapi_dict = swagger_to_openapi.convert_from_dict(swagger_content)

        state['openapi_content'] = converted_openapi_dict
        state['current_openapi_spec'] = converted_openapi_dict # Initialize for linting/correction cycle

        if state.get('verbose', True):
            print("Swagger 2.0 content successfully converted to OpenAPI 3.1.")
            # print(f"Converted OpenAPI version: {converted_openapi_dict.get('openapi')}")
            # print(f"Converted Info: {converted_openapi_dict.get('info', {}).get('title', 'Untitled')}")

    except Exception as e:
        error_msg = f"Failed to convert Swagger to OpenAPI: {str(e)}"
        state['error_message'] = error_msg
        if state.get('verbose', True): print(f"Error: {error_msg}")
        # Also print traceback for debugging if possible, or log it.
        import traceback
        if state.get('verbose', True): traceback.print_exc()

    return state

# Ensure json is imported (globally or locally)
# import json

def linting_node(state: AppState) -> AppState:
    verbose = state.get('verbose', True)
    if verbose: print(f"--- Linting Node (Iteration: {state.get('current_iteration', 0)}) ---")

    if state.get('error_message'):
        if verbose: print("Skipping linting due to existing error.")
        return state

    current_spec = state.get('current_openapi_spec')
    if not current_spec or not isinstance(current_spec, dict):
        state['error_message'] = "OpenAPI spec is missing or invalid for linting."
        if verbose: print(f"Error: {state['error_message']}")
        return state

    temp_file_path = None
    try:
        # Create a temporary file to store the spec for Redocly
        # Using NamedTemporaryFile to ensure it has a name for the subprocess
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.yaml', encoding='utf-8') as tmpfile:
            yaml.dump(current_spec, tmpfile, sort_keys=False, default_flow_style=False)
            temp_file_path = tmpfile.name

        if verbose: print(f"OpenAPI spec written to temporary file: {temp_file_path}")

        # Construct Redocly CLI command
        # Use `npx redocly lint ...` to avoid global installation issues if possible,
        # or assume redocly is in PATH. For a controlled environment, `redocly` directly is fine.
        # The requirement `redocly` in `requirements.txt` should make it available in the environment.
        command = ["redocly", "lint", temp_file_path, "--format=json"]

        if verbose: print(f"Executing linting command: {' '.join(command)}")

        # Execute the command
        process = subprocess.run(command, capture_output=True, text=True, check=False) # check=False to handle non-zero exit codes ourselves

        if verbose:
            print(f"Redocly CLI exited with code: {process.returncode}")
            if process.stdout:
                print(f"Redocly stdout (first 500 chars): {process.stdout[:500]}")
            if process.stderr:
                print(f"Redocly stderr: {process.stderr}")

        # Redocly CLI typically exits with non-zero code if there are issues.
        # The JSON output is usually on stdout.
        # If stderr has content, it might be actual errors from Redocly tool or just warnings.

        if not process.stdout and process.returncode != 0:
            # If no stdout and non-zero exit code, it's likely a tool execution error
            error_detail = process.stderr or "No output from Redocly CLI."
            state['error_message'] = f"Redocly CLI execution failed. Exit code: {process.returncode}. Error: {error_detail}"
            if verbose: print(f"Error: {state['error_message']}")
            state['linter_issues'] = [] # Ensure it's an empty list on error
            return state

        if not process.stdout:
            # No output, assume no issues if exit code was 0.
            if verbose: print("Redocly CLI produced no output. Assuming no linting issues.")
            state['linter_issues'] = []
            return state

        try:
            # Attempt to parse stdout as JSON, this should contain the linting issues
            linter_issues_output = json.loads(process.stdout)

            # The structure of Redocly's JSON output needs to be known.
            # Typically, it's an array of issue objects, or an object with a key containing the array.
            # Example: { "problems": [...], "summary": {...} } or just [...]
            # For Redocly, if issues are found, it's an array of problem objects.
            # If no issues, it might be an empty array, or some summary object.
            # `redocly lint demo.yaml --format=json` when no errors gives:
            # { total: 0, critical: 0, error: 0, warn: 0, info: 0 }
            # And when there are errors:
            # [ { ruleId: 'operation-description', message: 'Operation `description` must be present and non-empty string.', location: '#/paths/~1pets/get', severity: 'error', suggestedFix: null, from: null } ]

            if isinstance(linter_issues_output, list):
                state['linter_issues'] = linter_issues_output
            elif isinstance(linter_issues_output, dict) and 'problems' in linter_issues_output and isinstance(linter_issues_output['problems'], list):
                state['linter_issues'] = linter_issues_output['problems'] # More robust for some linters
            elif isinstance(linter_issues_output, dict) and linter_issues_output.get('total', -1) == 0 : # Redocly specific for no issues
                state['linter_issues'] = []
            else:
                # Unexpected JSON structure
                state['error_message'] = "Redocly CLI returned unexpected JSON structure."
                if verbose: print(f"Warning: {state['error_message']} Output: {process.stdout[:500]}")
                state['linter_issues'] = [] # Or a generic error issue
                # Could also try to extract from a known structure if the above check is too simple.
                # For now, if it's not a list directly, or 'problems' list, or total:0 dict, assume unexpected.
                # If Redocly always returns a list for issues, the check can be simpler.
                # Based on documentation, if problems exist, it's an array. If not, it's an object with counts.

            if verbose:
                if state['linter_issues']:
                    print(f"Linting found {len(state['linter_issues'])} issues.")
                    # for issue in state['linter_issues'][:3]: # Print first few issues
                    #    print(f"  - {issue.get('ruleId', 'N/A')}: {issue.get('message', 'No message')}")
                else:
                    print("Linting complete. No issues found.")

        except json.JSONDecodeError:
            # If stdout is not JSON, it might be an error message from Redocly or something else.
            state['error_message'] = f"Failed to parse Redocly CLI output as JSON. Output: {process.stdout[:500]}"
            if verbose: print(f"Error: {state['error_message']}")
            state['linter_issues'] = []
            # Consider if stderr had more info if stdout parsing fails
            if process.stderr and verbose:
                print(f"Redocly stderr (relevant if stdout parsing failed): {process.stderr}")

    except FileNotFoundError:
        state['error_message'] = "Redocly CLI not found. Please ensure it is installed and in PATH."
        if verbose: print(f"Error: {state['error_message']}")
        state['linter_issues'] = []
    except Exception as e:
        state['error_message'] = f"An error occurred during linting: {str(e)}"
        if verbose:
            print(f"Error: {state['error_message']}")
            import traceback
            traceback.print_exc()
        state['linter_issues'] = []
    finally:
        # Clean up the temporary file
        if temp_file_path and os.path.exists(temp_file_path):
            try:
                os.remove(temp_file_path)
                if verbose: print(f"Temporary file {temp_file_path} deleted.")
            except Exception as e_del:
                if verbose: print(f"Warning: Could not delete temporary file {temp_file_path}: {e_del}")
                # Log this, but don't overwrite a more critical error_message
                if not state.get('error_message'):
                    state['error_message'] = f"Warning: Failed to delete temp file {temp_file_path}."

    return state

# Attempt to load environment variables from .env file
load_dotenv()

def iterative_correction_node(state: AppState) -> AppState:
    verbose = state.get('verbose', True)
    current_iter = state.get('current_iteration', 0)
    if verbose: print(f"--- Iterative Correction Node (Iteration: {current_iter}) ---")

    if state.get('error_message'):
        if verbose: print("Skipping correction due to existing error.")
        return state

    linter_issues = state.get('linter_issues')
    if not linter_issues:
        if verbose: print("No linter issues found. Skipping correction.")
        # This case should ideally be handled by the conditional edge logic before reaching here.
        return state

    current_spec_dict = state.get('current_openapi_spec')
    if not current_spec_dict:
        state['error_message'] = "Current OpenAPI spec is missing for correction."
        if verbose: print(f"Error: {state['error_message']}")
        return state

    if verbose:
        print(f"Attempting to correct {len(linter_issues)} linter issues.")
        # print("Issues:", json.dumps(linter_issues, indent=2))

    try:
        # Initialize LLM
        # Ensure OPENAI_API_KEY is set in your environment or .env file
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            state['error_message'] = "OPENAI_API_KEY not found in environment."
            if verbose: print(f"Error: {state['error_message']}")
            return state

        # Using a common model, this can be configured further
        llm = ChatOpenAI(model_name="gpt-3.5-turbo", openai_api_key=api_key, temperature=0.3)

        current_spec_yaml = yaml.dump(current_spec_dict, sort_keys=False, default_flow_style=False)
        issues_json_str = json.dumps(linter_issues, indent=2)

        prompt_template = ChatPromptTemplate.from_messages([
            ("system",
             "You are an expert API designer specializing in OpenAPI specifications. "
             "Your task is to correct an OpenAPI 3.1 specification based on a list of linter issues. "
             "Analyze the provided OpenAPI YAML and the linter issues. "
             "Return ONLY the complete, corrected OpenAPI 3.1 specification as a single YAML block. "
             "Do not include any explanations, apologies, or introductory text outside the YAML block. "
             "Ensure your output is valid YAML. Focus on addressing all reported issues."),
            ("human",
             "Here is the current OpenAPI 3.1 specification (in YAML format):
"
             "```yaml
{current_spec}
```

"
             "Here are the linter issues that need to be addressed (in JSON format):
"
             "```json
{issues}
```

"
             "Please provide the full corrected OpenAPI 3.1 specification as a single YAML block:")
        ])

        chain = prompt_template | llm | StrOutputParser()

        if verbose: print("Invoking LLM for corrections...")

        corrected_spec_yaml_str = chain.invoke({
            "current_spec": current_spec_yaml,
            "issues": issues_json_str
        })

        if verbose: print(f"LLM raw response (first 500 chars): {corrected_spec_yaml_str[:500]}")

        # Attempt to parse the LLM's response (should be YAML)
        # Remove potential markdown backticks if LLM includes them
        if corrected_spec_yaml_str.strip().startswith("```yaml"):
            corrected_spec_yaml_str = corrected_spec_yaml_str.strip()[7:]
            if corrected_spec_yaml_str.strip().endswith("```"):
                 corrected_spec_yaml_str = corrected_spec_yaml_str.strip()[:-3]
        elif corrected_spec_yaml_str.strip().startswith("```"): # Generic backticks
            corrected_spec_yaml_str = corrected_spec_yaml_str.strip()[3:]
            if corrected_spec_yaml_str.strip().endswith("```"):
                 corrected_spec_yaml_str = corrected_spec_yaml_str.strip()[:-3]

        corrected_spec_yaml_str = corrected_spec_yaml_str.strip()

        if not corrected_spec_yaml_str:
            state['error_message'] = "LLM returned an empty response."
            # Keep the old spec, effectively a failed correction attempt for this round
            if verbose: print(f"Error: {state['error_message']}")
            # Increment iteration to avoid infinite loop if LLM keeps returning empty
            state['current_iteration'] = current_iter + 1
            return state

        new_spec_dict = yaml.safe_load(corrected_spec_yaml_str)

        if not isinstance(new_spec_dict, dict) or not new_spec_dict.get("openapi"):
             # Basic check if it looks like an OpenAPI spec
            state['error_message'] = "LLM output was not a valid OpenAPI YAML structure or was incomplete."
            if verbose: print(f"Error: {state['error_message']}. LLM output (stripped, first 300 chars): {corrected_spec_yaml_str[:300]}")
            # Keep the old spec
            state['current_iteration'] = current_iter + 1 # Increment to avoid potential loops
            return state

        state['current_openapi_spec'] = new_spec_dict
        if verbose: print("Successfully applied LLM corrections to the OpenAPI spec.")

    except Exception as e:
        error_msg = f"Error during LLM-based correction: {str(e)}"
        state['error_message'] = error_msg
        if verbose:
            print(f"Error: {error_msg}")
            import traceback
            traceback.print_exc()
        # Keep the old spec if LLM fails, but increment iteration to avoid getting stuck (if applicable)
        # The conditional logic `should_continue_correction` will check max_iterations.
        # If we don't increment, and LLM consistently fails, we might loop on the same iter count.

    state['current_iteration'] = current_iter + 1 # Increment iteration after attempt (success or caught error)
    if verbose: print(f"Iteration {state['current_iteration']} complete.")
    return state

def best_practices_node(state: AppState) -> AppState:
    verbose = state.get('verbose', True)
    if verbose: print("--- Best Practices Node ---")

    if state.get('error_message'):
        if verbose: print("Skipping best practices application due to existing error.")
        return state

    current_spec_dict = state.get('current_openapi_spec') # This is the lint-free spec
    if not current_spec_dict:
        state['error_message'] = "OpenAPI spec is missing for best practices application."
        if verbose: print(f"Error: {state['error_message']}")
        # Initialize final_openapi_spec to current_spec_dict to avoid None if error occurs here
        state['final_openapi_spec'] = current_spec_dict
        return state

    if verbose: print("Attempting to apply best practices to the OpenAPI spec.")

    try:
        # Initialize LLM (ensure OPENAI_API_KEY is set)
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            state['error_message'] = "OPENAI_API_KEY not found for BestPracticesAgent."
            if verbose: print(f"Error: {state['error_message']}")
            state['final_openapi_spec'] = current_spec_dict # Fallback
            return state

        llm = ChatOpenAI(model_name="gpt-4o", openai_api_key=api_key, temperature=0.5) # Using a more capable model potentially

        current_spec_yaml = yaml.dump(current_spec_dict, sort_keys=False, default_flow_style=False)

        prompt_template = ChatPromptTemplate.from_messages([
            ("system",
             "You are an expert API architect with deep knowledge of OpenAPI 3.1 best practices. "
             "Your task is to review and enhance an existing OpenAPI 3.1 specification. "
             "Focus on the following areas:
"
             "1.  **Examples**: Add diverse and realistic examples for request bodies and responses (especially for common status codes like 200, 201, 400, 401, 403, 404, 500). Ensure examples are rich and cover different scenarios where appropriate.
"
             "2.  **Descriptions**: Ensure all operations, parameters (path, query, header, cookie), request bodies, responses, schemas, and individual properties within schemas have clear, comprehensive, and user-friendly `description` fields. If descriptions are missing or too brief, expand them meaningfully.
"
             "3.  **Status Codes**: Verify the usage of HTTP status codes for semantic correctness. Ensure common success and error codes are used appropriately for each operation.
"
             "4.  **Tags**: Organize `tags` logically for better navigation and grouping of operations. Ensure tag names are descriptive and consistently used.
"
             "5.  **Components**: Promote reusability. Identify common data structures (schemas), parameters, or responses that can be defined in the `components` section and referenced using `$ref` elsewhere. Avoid redundancy.
"
             "Return ONLY the complete, enhanced OpenAPI 3.1 specification as a single YAML block. "
             "Do not include any explanations, apologies, or introductory text outside the YAML block. "
             "Preserve all existing functionality and data structures unless a change directly serves a best practice improvement (e.g., moving a schema to components)."),
            ("human",
             "Here is the current OpenAPI 3.1 specification (in YAML format):
"
             "```yaml
{current_spec}
```

"
             "Please apply the best practices mentioned above and provide the full, enhanced OpenAPI 3.1 specification as a single YAML block:")
        ])

        chain = prompt_template | llm | StrOutputParser()

        if verbose: print("Invoking LLM for best practice enhancements...")

        enhanced_spec_yaml_str = chain.invoke({
            "current_spec": current_spec_yaml
        })

        if verbose: print(f"LLM raw response for best practices (first 500 chars): {enhanced_spec_yaml_str[:500]}")

        # Attempt to parse the LLM's response (should be YAML)
        if enhanced_spec_yaml_str.strip().startswith("```yaml"):
            enhanced_spec_yaml_str = enhanced_spec_yaml_str.strip()[7:]
            if enhanced_spec_yaml_str.strip().endswith("```"):
                enhanced_spec_yaml_str = enhanced_spec_yaml_str.strip()[:-3]
        elif enhanced_spec_yaml_str.strip().startswith("```"):
             enhanced_spec_yaml_str = enhanced_spec_yaml_str.strip()[3:]
             if enhanced_spec_yaml_str.strip().endswith("```"):
                  enhanced_spec_yaml_str = enhanced_spec_yaml_str.strip()[:-3]

        enhanced_spec_yaml_str = enhanced_spec_yaml_str.strip()

        if not enhanced_spec_yaml_str:
            state['error_message'] = "LLM returned an empty response for best practices."
            if verbose: print(f"Error: {state['error_message']}")
            state['final_openapi_spec'] = current_spec_dict # Keep original if LLM fails
            return state

        new_enhanced_spec_dict = yaml.safe_load(enhanced_spec_yaml_str)

        if not isinstance(new_enhanced_spec_dict, dict) or not new_enhanced_spec_dict.get("openapi"):
            state['error_message'] = "LLM output for best practices was not a valid OpenAPI YAML structure."
            if verbose: print(f"Error: {state['error_message']}. LLM output (stripped, first 300 chars): {enhanced_spec_yaml_str[:300]}")
            state['final_openapi_spec'] = current_spec_dict # Keep original
            return state

        state['final_openapi_spec'] = new_enhanced_spec_dict
        if verbose: print("Successfully applied LLM-based best practice enhancements to the OpenAPI spec.")

    except Exception as e:
        error_msg = f"Error during LLM-based best practice application: {str(e)}"
        state['error_message'] = error_msg
        if verbose:
            print(f"Error: {error_msg}")
            import traceback
            traceback.print_exc()
        state['final_openapi_spec'] = current_spec_dict # Fallback to original on error

    return state

def impact_analysis_node(state: AppState) -> AppState:
    verbose = state.get('verbose', True)
    if verbose: print("--- Impact Analysis Node ---")

    if state.get('error_message') and not state.get('final_openapi_spec'): # Allow impact analysis if final spec exists despite earlier error
        if verbose: print("Skipping impact analysis due to critical existing error and no final spec.")
        state['impact_log'] = [{"tipo": "error", "descricao": "Impact analysis skipped due to critical preceding errors.", "acao_sugerida": "Review earlier errors."}]
        return state

    original_swagger = state.get('swagger_content')
    final_openapi = state.get('final_openapi_spec')

    if not original_swagger or not isinstance(original_swagger, dict):
        msg = "Original Swagger 2.0 content is missing or invalid for impact analysis."
        if verbose: print(f"Warning: {msg}")
        state['impact_log'] = [{"tipo": "warning", "descricao": msg, "acao_sugerida": "Ensure original Swagger is correctly loaded."}]
        # Allow to proceed if final_openapi exists, maybe some partial analysis or just note this.
        # If final_openapi is also missing, then it's a bigger issue.
        if not final_openapi or not isinstance(final_openapi, dict):
            state['error_message'] = (state.get('error_message') or "") + " Both original and final specs missing for impact analysis."
            state['impact_log'] = [{"tipo": "error", "descricao": state['error_message'], "acao_sugerida": "Check entire workflow."}]
            return state

    if not final_openapi or not isinstance(final_openapi, dict):
        msg = "Final OpenAPI 3.1 spec is missing or invalid for impact analysis."
        if verbose: print(f"Error: {msg}")
        state['error_message'] = (state.get('error_message') or "") + f"; {msg}"
        state['impact_log'] = [{"tipo": "error", "descricao": msg, "acao_sugerida": "Ensure best practices node ran successfully or check for errors."}]
        return state

    if verbose: print("Attempting to analyze impact between original Swagger 2.0 and final OpenAPI 3.1 spec.")

    try:
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            state['error_message'] = "OPENAI_API_KEY not found for ImpactAnalysisAgent."
            if verbose: print(f"Error: {state['error_message']}")
            state['impact_log'] = [{"tipo": "error", "descricao": state['error_message'], "acao_sugerida": "Set OPENAI_API_KEY."}]
            return state

        # Using a capable model for comparison tasks
        llm = ChatOpenAI(model_name="gpt-4o", openai_api_key=api_key, temperature=0.3)

        original_spec_yaml = yaml.dump(original_swagger, sort_keys=False, default_flow_style=False)
        final_spec_yaml = yaml.dump(final_openapi, sort_keys=False, default_flow_style=False)

        prompt_template = ChatPromptTemplate.from_messages([
            ("system",
             "You are an expert API versioning and migration analyst. Your task is to compare an original Swagger 2.0 specification with a new OpenAPI 3.1 specification that has been converted and enhanced. "
             "Identify all changes that are potentially breaking for existing API consumers or require significant developer attention. "
             "Focus on changes such as:
"
             "- Path renaming, removal, or significant structural changes.
"
             "- HTTP method changes for existing paths (e.g., GET to POST).
"
             "- Parameter (query, path, header) renaming, removal, type changes, or changes in 'required' status.
"
             "- Request body structure changes: field renaming, removal, addition of new *required* fields, data type changes of existing fields.
"
             "- Response body structure changes for existing status codes: field renaming, removal, data type changes.
"
             "- Removal of operations or entire paths.
"
             "- Changes in authentication/authorization schemes if discernible.
"
             "- Significant changes in enumerated values for parameters or schema properties.
"
             "For each identified change, provide a JSON object with the following keys:
"
             "  - `tipo`: A string indicating the type of change (e.g., 'breaking_change', 'potentially_breaking_change', 'significant_improvement', 'minor_change', 'deprecation_warning').
"
             "  - `descricao`: A clear, concise description of what changed, including path, method, parameter/field names where applicable.
"
             "  - `acao_sugerida`: A recommended action for developers consuming this API (e.g., 'Update client to use new parameter name X.', 'Verify compatibility with new response structure for endpoint Y.').
"
             "Return ONLY a single JSON array containing these objects. Do not include any explanations, apologies, or introductory text outside the JSON array. If no significant changes are found, return an empty JSON array []."
            ),
            ("human",
             "Original Swagger 2.0 Specification (YAML):
"
             "```yaml
{original_spec}
```

"
             "New OpenAPI 3.1 Specification (YAML):
"
             "```yaml
{final_spec}
```

"
             "Please provide the JSON array of identified changes:")
        ])

        chain = prompt_template | llm | StrOutputParser()

        if verbose: print("Invoking LLM for impact analysis...")

        impact_json_str = chain.invoke({
            "original_spec": original_spec_yaml,
            "final_spec": final_spec_yaml
        })

        if verbose: print(f"LLM raw response for impact analysis (first 500 chars): {impact_json_str[:500]}")

        # Attempt to parse the LLM's response (should be JSON array)
        if impact_json_str.strip().startswith("```json"):
            impact_json_str = impact_json_str.strip()[7:] # remove ```json
            if impact_json_str.strip().endswith("```"):
                 impact_json_str = impact_json_str.strip()[:-3] # remove ```
        elif impact_json_str.strip().startswith("```"): # Generic backticks
             impact_json_str = impact_json_str.strip()[3:]
             if impact_json_str.strip().endswith("```"):
                  impact_json_str = impact_json_str.strip()[:-3]

        impact_json_str = impact_json_str.strip()

        if not impact_json_str:
            # If LLM returns empty string, assume no changes or failure to produce output
            if verbose: print("LLM returned an empty response for impact analysis. Assuming no changes or LLM error.")
            state['impact_log'] = [] # Default to no changes if LLM is silent
            # Could set a warning in impact_log if this is unexpected
            # state['impact_log'] = [{"tipo": "warning", "descricao": "LLM provided no output for impact analysis.", "acao_sugerida": "Manual review might be needed if changes were expected."}]
            return state

        impact_data = json.loads(impact_json_str)

        if not isinstance(impact_data, list):
            msg = "LLM output for impact analysis was not a valid JSON array."
            if verbose: print(f"Error: {msg} Output (stripped): {impact_json_str[:300]}")
            state['error_message'] = (state.get('error_message') or "") + f"; {msg}"
            state['impact_log'] = [{"tipo": "error", "descricao": msg, "acao_sugerida": "Check LLM prompt or model behavior."}]
            return state

        # Optional: Validate structure of each object in impact_data
        validated_impact_log = []
        for item in impact_data:
            if isinstance(item, dict) and 'tipo' in item and 'descricao' in item and 'acao_sugerida' in item:
                validated_impact_log.append(item)
            else:
                if verbose: print(f"Warning: LLM returned a malformed item in impact analysis: {item}")
                validated_impact_log.append({
                    "tipo": "error_malformed_item",
                    "descricao": f"LLM returned a malformed item: {str(item)[:100]}",
                    "acao_sugerida": "Review LLM output for this item."
                })

        state['impact_log'] = validated_impact_log
        if verbose: print(f"Impact analysis complete. Found {len(validated_impact_log)} items.")

    except json.JSONDecodeError as e:
        msg = f"Failed to parse LLM JSON response for impact analysis: {str(e)}. Response (first 300 chars): {impact_json_str[:300]}"
        if verbose: print(f"Error: {msg}")
        state['error_message'] = (state.get('error_message') or "") + f"; {msg}"
        state['impact_log'] = [{"tipo": "error", "descricao": msg, "acao_sugerida": "Check LLM output, may not be valid JSON."}]
    except Exception as e:
        error_msg = f"Error during LLM-based impact analysis: {str(e)}"
        state['error_message'] = (state.get('error_message') or "") + f"; {error_msg}"
        if verbose:
            print(f"Error: {error_msg}")
            import traceback
            traceback.print_exc()
        state['impact_log'] = [{"tipo": "error", "descricao": error_msg, "acao_sugerida": "Review system logs for ImpactAnalysisAgent."}]

    return state

# --- Conditional Edges ---

def should_continue_correction(state: AppState) -> str:
    print(f"--- Condition: Should Continue Correction? (Iteration {state['current_iteration']}) ---")
    if state.get('error_message'):
        print("Error detected, stopping corrections.")
        return "end_workflow" # Or an error handling node

    if not state.get('linter_issues'):
        print("No linter issues found. Proceeding to best practices.")
        return "apply_best_practices"

    if state['current_iteration'] >= state.get('max_iterations', 5): # Max iterations check
        print(f"Max iterations ({state['max_iterations']}) reached. Proceeding despite remaining issues.")
        # Optionally, log a warning or set a flag here
        state['error_message'] = "Max iterations reached during correction. Issues might remain."
        return "apply_best_practices" # Or go to an error/warning summary node

    print(f"Linter issues exist and iterations ({state['current_iteration']}) < max ({state.get('max_iterations',5)}). Continuing correction.")
    return "correct_issues"

def check_for_errors(state: AppState) -> str:
    print("--- Condition: Check for errors ---")
    if state.get('error_message'):
        print(f"Error occurred: {state['error_message']}. Ending workflow.")
        return "end_workflow" # Or a dedicated error reporting node
    return "continue_workflow" # A general name for the next step if no specific branch

# --- Graph Definition ---
workflow = StateGraph(AppState)

# Add nodes
workflow.add_node("reader_validator", reader_validator_node)
workflow.add_node("converter", conversion_node)
workflow.add_node("linter", linting_node)
workflow.add_node("corrector", iterative_correction_node)
workflow.add_node("best_practicer", best_practices_node)
workflow.add_node("impact_analyzer", impact_analysis_node)
workflow.add_node("error_handler_node", END) # A simple way to end on error for now

# Set entry point
workflow.set_entry_point("reader_validator")

# Add edges
# workflow.add_edge("reader_validator", "converter") # TODO: Add error handling from reader
# This line above is replaced by the conditional edge below

workflow.add_conditional_edges(
    "reader_validator",
    check_for_errors,
    {
        "continue_workflow": "converter",
        "end_workflow": "error_handler_node" # Using the simple END for now
    }
)

# workflow.add_edge("converter", "linter") # Initial linting run
# This line above is replaced by the conditional edge below
workflow.add_conditional_edges(
    "converter",
    check_for_errors, # Check for errors after conversion
    {
        "continue_workflow": "linter",
        "end_workflow": "error_handler_node"
    }
)

workflow.add_conditional_edges(
    "linter",
    should_continue_correction,
    {
        "correct_issues": "corrector",
        "apply_best_practices": "best_practicer",
        "end_workflow": "error_handler_node" # If error in should_continue_correction's state
    }
)
workflow.add_edge("corrector", "linter") # Loop back to linter after correction

# workflow.add_edge("best_practicer", "impact_analyzer")
# This line above is replaced by the conditional edge below
workflow.add_conditional_edges(
    "best_practicer",
    check_for_errors, # Check for errors after best practices
    {
        "continue_workflow": "impact_analyzer",
        "end_workflow": "error_handler_node"
    }
)

workflow.add_edge("impact_analyzer", END) # Final step

# Compile the graph
app = workflow.compile()

# Add a simple test invocation for development (optional, can be removed later)
if __name__ == "__main__":
    print("Testing workflow graph independently...")
    initial_state_test = {
        "original_swagger_file_path": "dummy_path.yaml", # Needs a dummy file or mock loading
        "swagger_content": {"swagger": "2.0", "info": {"title": "Test Swagger"}}, # Preload for test
        "openapi_content": None,
        "current_openapi_spec": None,
        "linter_issues": [],
        "impact_log": [],
        "final_openapi_spec": None,
        "current_iteration": 0,
        "max_iterations": 3, # Test with fewer iterations
        "error_message": None,
        "verbose": True
    }

    # To run this test standalone, you might need to mock file operations
    # or ensure a dummy_path.yaml exists.
    # For now, this part will likely fail if dummy_path.yaml doesn't exist and reader_validator_node tries to open it.
    # The main script `src/main.py` will be the primary way to run this.

    # Create a dummy file for testing if it doesn't exist
    import os
    if not os.path.exists("dummy_path.yaml"):
        with open("dummy_path.yaml", "w") as f:
            yaml.dump({"swagger": "2.0", "info": {"title": "Test Swagger from dummy_path.yaml"}}, f)
            print("Created dummy_path.yaml for testing.")

    print(f"Initial state for test: {initial_state_test}")
    final_state_test = None
    try:
        # If reader_validator_node is robust enough, it might use the preloaded swagger_content
        # or try to load from original_swagger_file_path.
        # Let's ensure swagger_content is NOT preloaded to test the reader_validator_node file loading
        initial_state_test_for_load = initial_state_test.copy()
        initial_state_test_for_load["swagger_content"] = None # Force loading

        final_state_test = app.invoke(initial_state_test_for_load)
        print("\n--- Workflow Test Finished ---")
        print(f"Final state from test: {yaml.dump(final_state_test)}") # Using yaml.dump for pretty print

        if final_state_test.get("error_message"):
            print(f"Error in workflow: {final_state_test['error_message']}")
        if final_state_test.get("final_openapi_spec"):
            print(f"Final Spec Title: {final_state_test['final_openapi_spec']['info'].get('title')}")
            print(f"Final Spec Description: {final_state_test['final_openapi_spec']['info'].get('description')}")
        if final_state_test.get("impact_log"):
            print(f"Impact Log: {final_state_test['impact_log']}")

    except Exception as e:
        print(f"Exception during workflow test: {e}")
    finally:
        # Clean up dummy file
        if os.path.exists("dummy_path.yaml"):
            os.remove("dummy_path.yaml")
            print("Cleaned up dummy_path.yaml.")
